name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on versioned tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Adjust to your Go version

      # Build the binary
      - name: Build the project
        run: go build -o dns-changer

      # Archive the binary
      - name: Create archive
        run: tar -czvf dns-changer.tar.gz dns-changer

      # Upload to GitHub Releases
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dns-changer.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
